// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.24.4
// source: proto/caregiver.proto

package pb

import (
	reflect "reflect"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Caregiver struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name      string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Birthdate *Date  `protobuf:"bytes,3,opt,name=birthdate,proto3" json:"birthdate,omitempty"`
	Avatar    string `protobuf:"bytes,4,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Sex       Sex    `protobuf:"varint,5,opt,name=sex,proto3,enum=pb.Sex" json:"sex,omitempty"`
	Status    string `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	Email     string `protobuf:"bytes,7,opt,name=email,proto3" json:"email,omitempty"`
}

func (x *Caregiver) Reset() {
	*x = Caregiver{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_caregiver_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Caregiver) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Caregiver) ProtoMessage() {}

func (x *Caregiver) ProtoReflect() protoreflect.Message {
	mi := &file_proto_caregiver_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Caregiver.ProtoReflect.Descriptor instead.
func (*Caregiver) Descriptor() ([]byte, []int) {
	return file_proto_caregiver_proto_rawDescGZIP(), []int{0}
}

func (x *Caregiver) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Caregiver) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Caregiver) GetBirthdate() *Date {
	if x != nil {
		return x.Birthdate
	}
	return nil
}

func (x *Caregiver) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *Caregiver) GetSex() Sex {
	if x != nil {
		return x.Sex
	}
	return Sex_UNDEFINED
}

func (x *Caregiver) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Caregiver) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type CaregiverFull struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name      string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Birthdate *Date    `protobuf:"bytes,3,opt,name=birthdate,proto3" json:"birthdate,omitempty"`
	Avatar    string   `protobuf:"bytes,4,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Sex       Sex      `protobuf:"varint,5,opt,name=sex,proto3,enum=pb.Sex" json:"sex,omitempty"`
	Status    string   `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	Patient   *Patient `protobuf:"bytes,7,opt,name=patient,proto3" json:"patient,omitempty"`
	Email     string   `protobuf:"bytes,8,opt,name=email,proto3" json:"email,omitempty"`
}

func (x *CaregiverFull) Reset() {
	*x = CaregiverFull{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_caregiver_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CaregiverFull) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaregiverFull) ProtoMessage() {}

func (x *CaregiverFull) ProtoReflect() protoreflect.Message {
	mi := &file_proto_caregiver_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaregiverFull.ProtoReflect.Descriptor instead.
func (*CaregiverFull) Descriptor() ([]byte, []int) {
	return file_proto_caregiver_proto_rawDescGZIP(), []int{1}
}

func (x *CaregiverFull) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CaregiverFull) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CaregiverFull) GetBirthdate() *Date {
	if x != nil {
		return x.Birthdate
	}
	return nil
}

func (x *CaregiverFull) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *CaregiverFull) GetSex() Sex {
	if x != nil {
		return x.Sex
	}
	return Sex_UNDEFINED
}

func (x *CaregiverFull) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CaregiverFull) GetPatient() *Patient {
	if x != nil {
		return x.Patient
	}
	return nil
}

func (x *CaregiverFull) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type CreateCaregiverRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name      string  `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Birthdate *Date   `protobuf:"bytes,2,opt,name=birthdate,proto3" json:"birthdate,omitempty"`
	Avatar    *string `protobuf:"bytes,3,opt,name=avatar,proto3,oneof" json:"avatar,omitempty"`
	Sex       Sex     `protobuf:"varint,4,opt,name=sex,proto3,enum=pb.Sex" json:"sex,omitempty"`
	Email     string  `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
}

func (x *CreateCaregiverRequest) Reset() {
	*x = CreateCaregiverRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_caregiver_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateCaregiverRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCaregiverRequest) ProtoMessage() {}

func (x *CreateCaregiverRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_caregiver_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCaregiverRequest.ProtoReflect.Descriptor instead.
func (*CreateCaregiverRequest) Descriptor() ([]byte, []int) {
	return file_proto_caregiver_proto_rawDescGZIP(), []int{2}
}

func (x *CreateCaregiverRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateCaregiverRequest) GetBirthdate() *Date {
	if x != nil {
		return x.Birthdate
	}
	return nil
}

func (x *CreateCaregiverRequest) GetAvatar() string {
	if x != nil && x.Avatar != nil {
		return *x.Avatar
	}
	return ""
}

func (x *CreateCaregiverRequest) GetSex() Sex {
	if x != nil {
		return x.Sex
	}
	return Sex_UNDEFINED
}

func (x *CreateCaregiverRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type UpdateCaregiverRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Birthdate   *Date  `protobuf:"bytes,2,opt,name=birthdate,proto3" json:"birthdate,omitempty"`
	Avatar      string `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Sex         Sex    `protobuf:"varint,4,opt,name=sex,proto3,enum=pb.Sex" json:"sex,omitempty"`
	Email       string `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	CaregiverId uint64 `protobuf:"varint,6,opt,name=caregiver_id,json=caregiverId,proto3" json:"caregiver_id,omitempty"`
}

func (x *UpdateCaregiverRequest) Reset() {
	*x = UpdateCaregiverRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_caregiver_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateCaregiverRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCaregiverRequest) ProtoMessage() {}

func (x *UpdateCaregiverRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_caregiver_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCaregiverRequest.ProtoReflect.Descriptor instead.
func (*UpdateCaregiverRequest) Descriptor() ([]byte, []int) {
	return file_proto_caregiver_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateCaregiverRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateCaregiverRequest) GetBirthdate() *Date {
	if x != nil {
		return x.Birthdate
	}
	return nil
}

func (x *UpdateCaregiverRequest) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *UpdateCaregiverRequest) GetSex() Sex {
	if x != nil {
		return x.Sex
	}
	return Sex_UNDEFINED
}

func (x *UpdateCaregiverRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UpdateCaregiverRequest) GetCaregiverId() uint64 {
	if x != nil {
		return x.CaregiverId
	}
	return 0
}

type FindCaregiverByIDRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *FindCaregiverByIDRequest) Reset() {
	*x = FindCaregiverByIDRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_caregiver_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindCaregiverByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindCaregiverByIDRequest) ProtoMessage() {}

func (x *FindCaregiverByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_caregiver_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindCaregiverByIDRequest.ProtoReflect.Descriptor instead.
func (*FindCaregiverByIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_caregiver_proto_rawDescGZIP(), []int{4}
}

func (x *FindCaregiverByIDRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteCaregiverRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteCaregiverRequest) Reset() {
	*x = DeleteCaregiverRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_caregiver_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteCaregiverRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCaregiverRequest) ProtoMessage() {}

func (x *DeleteCaregiverRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_caregiver_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCaregiverRequest.ProtoReflect.Descriptor instead.
func (*DeleteCaregiverRequest) Descriptor() ([]byte, []int) {
	return file_proto_caregiver_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteCaregiverRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type AddPatientRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CaregiverId uint64 `protobuf:"varint,1,opt,name=caregiver_id,json=caregiverId,proto3" json:"caregiver_id,omitempty"`
	PatientId   uint64 `protobuf:"varint,2,opt,name=patient_id,json=patientId,proto3" json:"patient_id,omitempty"`
}

func (x *AddPatientRequest) Reset() {
	*x = AddPatientRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_caregiver_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddPatientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPatientRequest) ProtoMessage() {}

func (x *AddPatientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_caregiver_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPatientRequest.ProtoReflect.Descriptor instead.
func (*AddPatientRequest) Descriptor() ([]byte, []int) {
	return file_proto_caregiver_proto_rawDescGZIP(), []int{6}
}

func (x *AddPatientRequest) GetCaregiverId() uint64 {
	if x != nil {
		return x.CaregiverId
	}
	return 0
}

func (x *AddPatientRequest) GetPatientId() uint64 {
	if x != nil {
		return x.PatientId
	}
	return 0
}

type LinkPatientDeviceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PatientSessionToken string `protobuf:"bytes,1,opt,name=patient_session_token,json=patientSessionToken,proto3" json:"patient_session_token,omitempty"`
}

func (x *LinkPatientDeviceRequest) Reset() {
	*x = LinkPatientDeviceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_caregiver_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LinkPatientDeviceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinkPatientDeviceRequest) ProtoMessage() {}

func (x *LinkPatientDeviceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_caregiver_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinkPatientDeviceRequest.ProtoReflect.Descriptor instead.
func (*LinkPatientDeviceRequest) Descriptor() ([]byte, []int) {
	return file_proto_caregiver_proto_rawDescGZIP(), []int{7}
}

func (x *LinkPatientDeviceRequest) GetPatientSessionToken() string {
	if x != nil {
		return x.PatientSessionToken
	}
	return ""
}

var File_proto_caregiver_proto protoreflect.FileDescriptor

var file_proto_caregiver_proto_rawDesc = []byte{
	0x0a, 0x15, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x61, 0x72, 0x65, 0x67, 0x69, 0x76, 0x65,
	0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x1a, 0x13, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2f, 0x70, 0x61, 0x74, 0x69, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x11, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x75, 0x74, 0x69, 0x6c, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0xb8, 0x01, 0x0a, 0x09, 0x43, 0x61, 0x72, 0x65, 0x67, 0x69, 0x76, 0x65,
	0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x26, 0x0a, 0x09, 0x62, 0x69, 0x72, 0x74, 0x68, 0x64, 0x61,
	0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x70, 0x62, 0x2e, 0x44, 0x61,
	0x74, 0x65, 0x52, 0x09, 0x62, 0x69, 0x72, 0x74, 0x68, 0x64, 0x61, 0x74, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61,
	0x76, 0x61, 0x74, 0x61, 0x72, 0x12, 0x19, 0x0a, 0x03, 0x73, 0x65, 0x78, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x07, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x65, 0x78, 0x52, 0x03, 0x73, 0x65, 0x78,
	0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69,
	0x6c, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x22, 0xe3,
	0x01, 0x0a, 0x0d, 0x43, 0x61, 0x72, 0x65, 0x67, 0x69, 0x76, 0x65, 0x72, 0x46, 0x75, 0x6c, 0x6c,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x26, 0x0a, 0x09, 0x62, 0x69, 0x72, 0x74, 0x68, 0x64, 0x61, 0x74,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x70, 0x62, 0x2e, 0x44, 0x61, 0x74,
	0x65, 0x52, 0x09, 0x62, 0x69, 0x72, 0x74, 0x68, 0x64, 0x61, 0x74, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x76,
	0x61, 0x74, 0x61, 0x72, 0x12, 0x19, 0x0a, 0x03, 0x73, 0x65, 0x78, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x07, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x65, 0x78, 0x52, 0x03, 0x73, 0x65, 0x78, 0x12,
	0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x25, 0x0a, 0x07, 0x70, 0x61, 0x74, 0x69, 0x65,
	0x6e, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x61,
	0x74, 0x69, 0x65, 0x6e, 0x74, 0x52, 0x07, 0x70, 0x61, 0x74, 0x69, 0x65, 0x6e, 0x74, 0x12, 0x14,
	0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65,
	0x6d, 0x61, 0x69, 0x6c, 0x22, 0xad, 0x01, 0x0a, 0x16, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43,
	0x61, 0x72, 0x65, 0x67, 0x69, 0x76, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x26, 0x0a, 0x09, 0x62, 0x69, 0x72, 0x74, 0x68, 0x64, 0x61, 0x74, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x70, 0x62, 0x2e, 0x44, 0x61, 0x74, 0x65,
	0x52, 0x09, 0x62, 0x69, 0x72, 0x74, 0x68, 0x64, 0x61, 0x74, 0x65, 0x12, 0x1b, 0x0a, 0x06, 0x61,
	0x76, 0x61, 0x74, 0x61, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x06, 0x61,
	0x76, 0x61, 0x74, 0x61, 0x72, 0x88, 0x01, 0x01, 0x12, 0x19, 0x0a, 0x03, 0x73, 0x65, 0x78, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x07, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x65, 0x78, 0x52, 0x03,
	0x73, 0x65, 0x78, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x61, 0x76,
	0x61, 0x74, 0x61, 0x72, 0x22, 0xc0, 0x01, 0x0a, 0x16, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43,
	0x61, 0x72, 0x65, 0x67, 0x69, 0x76, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x26, 0x0a, 0x09, 0x62, 0x69, 0x72, 0x74, 0x68, 0x64, 0x61, 0x74, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x70, 0x62, 0x2e, 0x44, 0x61, 0x74, 0x65,
	0x52, 0x09, 0x62, 0x69, 0x72, 0x74, 0x68, 0x64, 0x61, 0x74, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x61,
	0x76, 0x61, 0x74, 0x61, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x76, 0x61,
	0x74, 0x61, 0x72, 0x12, 0x19, 0x0a, 0x03, 0x73, 0x65, 0x78, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x07, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x65, 0x78, 0x52, 0x03, 0x73, 0x65, 0x78, 0x12, 0x14,
	0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65,
	0x6d, 0x61, 0x69, 0x6c, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x61, 0x72, 0x65, 0x67, 0x69, 0x76, 0x65,
	0x72, 0x5f, 0x69, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0b, 0x63, 0x61, 0x72, 0x65,
	0x67, 0x69, 0x76, 0x65, 0x72, 0x49, 0x64, 0x22, 0x2a, 0x0a, 0x18, 0x46, 0x69, 0x6e, 0x64, 0x43,
	0x61, 0x72, 0x65, 0x67, 0x69, 0x76, 0x65, 0x72, 0x42, 0x79, 0x49, 0x44, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x02, 0x69, 0x64, 0x22, 0x28, 0x0a, 0x16, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x61, 0x72,
	0x65, 0x67, 0x69, 0x76, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x22, 0x55, 0x0a,
	0x11, 0x41, 0x64, 0x64, 0x50, 0x61, 0x74, 0x69, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x61, 0x72, 0x65, 0x67, 0x69, 0x76, 0x65, 0x72, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0b, 0x63, 0x61, 0x72, 0x65, 0x67, 0x69,
	0x76, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x61, 0x74, 0x69, 0x65, 0x6e, 0x74,
	0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x70, 0x61, 0x74, 0x69, 0x65,
	0x6e, 0x74, 0x49, 0x64, 0x22, 0x4e, 0x0a, 0x18, 0x4c, 0x69, 0x6e, 0x6b, 0x50, 0x61, 0x74, 0x69,
	0x65, 0x6e, 0x74, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x32, 0x0a, 0x15, 0x70, 0x61, 0x74, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x73, 0x65, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x13, 0x70, 0x61, 0x74, 0x69, 0x65, 0x6e, 0x74, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x54,
	0x6f, 0x6b, 0x65, 0x6e, 0x32, 0xdf, 0x02, 0x0a, 0x10, 0x43, 0x61, 0x72, 0x65, 0x67, 0x69, 0x76,
	0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x33, 0x0a, 0x06, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x12, 0x1a, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43,
	0x61, 0x72, 0x65, 0x67, 0x69, 0x76, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x0d, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x61, 0x72, 0x65, 0x67, 0x69, 0x76, 0x65, 0x72, 0x12, 0x3b,
	0x0a, 0x08, 0x46, 0x69, 0x6e, 0x64, 0x42, 0x79, 0x49, 0x64, 0x12, 0x1c, 0x2e, 0x70, 0x62, 0x2e,
	0x46, 0x69, 0x6e, 0x64, 0x43, 0x61, 0x72, 0x65, 0x67, 0x69, 0x76, 0x65, 0x72, 0x42, 0x79, 0x49,
	0x44, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x11, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x61,
	0x72, 0x65, 0x67, 0x69, 0x76, 0x65, 0x72, 0x46, 0x75, 0x6c, 0x6c, 0x12, 0x2f, 0x0a, 0x06, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x1a, 0x2e, 0x70, 0x62, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x43, 0x61, 0x72, 0x65, 0x67, 0x69, 0x76, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x09, 0x2e, 0x70, 0x62, 0x2e, 0x42, 0x6c, 0x61, 0x6e, 0x6b, 0x12, 0x2f, 0x0a, 0x06,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x1a, 0x2e, 0x70, 0x62, 0x2e, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x43, 0x61, 0x72, 0x65, 0x67, 0x69, 0x76, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x09, 0x2e, 0x70, 0x62, 0x2e, 0x42, 0x6c, 0x61, 0x6e, 0x6b, 0x12, 0x39, 0x0a,
	0x0d, 0x41, 0x64, 0x64, 0x4e, 0x65, 0x77, 0x50, 0x61, 0x74, 0x69, 0x65, 0x6e, 0x74, 0x12, 0x15,
	0x2e, 0x70, 0x62, 0x2e, 0x41, 0x64, 0x64, 0x50, 0x61, 0x74, 0x69, 0x65, 0x6e, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x11, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x61, 0x72, 0x65, 0x67,
	0x69, 0x76, 0x65, 0x72, 0x46, 0x75, 0x6c, 0x6c, 0x12, 0x3c, 0x0a, 0x11, 0x4c, 0x69, 0x6e, 0x6b,
	0x50, 0x61, 0x74, 0x69, 0x65, 0x6e, 0x74, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x12, 0x1c, 0x2e,
	0x70, 0x62, 0x2e, 0x4c, 0x69, 0x6e, 0x6b, 0x50, 0x61, 0x74, 0x69, 0x65, 0x6e, 0x74, 0x44, 0x65,
	0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x09, 0x2e, 0x70, 0x62,
	0x2e, 0x42, 0x6c, 0x61, 0x6e, 0x6b, 0x42, 0x1c, 0x5a, 0x1a, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e,
	0x61, 0x6c, 0x2f, 0x69, 0x6e, 0x66, 0x72, 0x61, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x75, 0x72,
	0x65, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_caregiver_proto_rawDescOnce sync.Once
	file_proto_caregiver_proto_rawDescData = file_proto_caregiver_proto_rawDesc
)

func file_proto_caregiver_proto_rawDescGZIP() []byte {
	file_proto_caregiver_proto_rawDescOnce.Do(func() {
		file_proto_caregiver_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_caregiver_proto_rawDescData)
	})
	return file_proto_caregiver_proto_rawDescData
}

var file_proto_caregiver_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_caregiver_proto_goTypes = []interface{}{
	(*Caregiver)(nil),                // 0: pb.Caregiver
	(*CaregiverFull)(nil),            // 1: pb.CaregiverFull
	(*CreateCaregiverRequest)(nil),   // 2: pb.CreateCaregiverRequest
	(*UpdateCaregiverRequest)(nil),   // 3: pb.UpdateCaregiverRequest
	(*FindCaregiverByIDRequest)(nil), // 4: pb.FindCaregiverByIDRequest
	(*DeleteCaregiverRequest)(nil),   // 5: pb.DeleteCaregiverRequest
	(*AddPatientRequest)(nil),        // 6: pb.AddPatientRequest
	(*LinkPatientDeviceRequest)(nil), // 7: pb.LinkPatientDeviceRequest
	(*Date)(nil),                     // 8: pb.Date
	(Sex)(0),                         // 9: pb.Sex
	(*Patient)(nil),                  // 10: pb.Patient
	(*Blank)(nil),                    // 11: pb.Blank
}
var file_proto_caregiver_proto_depIdxs = []int32{
	8,  // 0: pb.Caregiver.birthdate:type_name -> pb.Date
	9,  // 1: pb.Caregiver.sex:type_name -> pb.Sex
	8,  // 2: pb.CaregiverFull.birthdate:type_name -> pb.Date
	9,  // 3: pb.CaregiverFull.sex:type_name -> pb.Sex
	10, // 4: pb.CaregiverFull.patient:type_name -> pb.Patient
	8,  // 5: pb.CreateCaregiverRequest.birthdate:type_name -> pb.Date
	9,  // 6: pb.CreateCaregiverRequest.sex:type_name -> pb.Sex
	8,  // 7: pb.UpdateCaregiverRequest.birthdate:type_name -> pb.Date
	9,  // 8: pb.UpdateCaregiverRequest.sex:type_name -> pb.Sex
	2,  // 9: pb.CaregiverService.Create:input_type -> pb.CreateCaregiverRequest
	4,  // 10: pb.CaregiverService.FindById:input_type -> pb.FindCaregiverByIDRequest
	3,  // 11: pb.CaregiverService.Update:input_type -> pb.UpdateCaregiverRequest
	5,  // 12: pb.CaregiverService.Delete:input_type -> pb.DeleteCaregiverRequest
	6,  // 13: pb.CaregiverService.AddNewPatient:input_type -> pb.AddPatientRequest
	7,  // 14: pb.CaregiverService.LinkPatientDevice:input_type -> pb.LinkPatientDeviceRequest
	0,  // 15: pb.CaregiverService.Create:output_type -> pb.Caregiver
	1,  // 16: pb.CaregiverService.FindById:output_type -> pb.CaregiverFull
	11, // 17: pb.CaregiverService.Update:output_type -> pb.Blank
	11, // 18: pb.CaregiverService.Delete:output_type -> pb.Blank
	1,  // 19: pb.CaregiverService.AddNewPatient:output_type -> pb.CaregiverFull
	11, // 20: pb.CaregiverService.LinkPatientDevice:output_type -> pb.Blank
	15, // [15:21] is the sub-list for method output_type
	9,  // [9:15] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_proto_caregiver_proto_init() }
func file_proto_caregiver_proto_init() {
	if File_proto_caregiver_proto != nil {
		return
	}
	file_proto_patient_proto_init()
	file_proto_utils_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_proto_caregiver_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Caregiver); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_caregiver_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CaregiverFull); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_caregiver_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateCaregiverRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_caregiver_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateCaregiverRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_caregiver_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindCaregiverByIDRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_caregiver_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteCaregiverRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_caregiver_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddPatientRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_caregiver_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LinkPatientDeviceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_proto_caregiver_proto_msgTypes[2].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_caregiver_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_caregiver_proto_goTypes,
		DependencyIndexes: file_proto_caregiver_proto_depIdxs,
		MessageInfos:      file_proto_caregiver_proto_msgTypes,
	}.Build()
	File_proto_caregiver_proto = out.File
	file_proto_caregiver_proto_rawDesc = nil
	file_proto_caregiver_proto_goTypes = nil
	file_proto_caregiver_proto_depIdxs = nil
}
